name: build

on:
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Setup node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - run: npm ci
      - run: npm install -g @angular/cli
      - run: ng build -c production 

  
